FORMAT: 1A
HOST: https://et-api-example.com/

# ET Forms API
This API replaces an existing Jadu system, enabling full functionality within ET1 and ET3 forms.

# Group ET1 [/claimants]
Group of all ET1-related resources.

This group is primarily focussed on the ET1 web form.

# Group ET3 [/respondents]
Group of all ET3-related resources.

This group is primarily focussed on the ET3 web form.

## Response [/respondents/response]
Creates a respondent response within the system and returns confirmation.

### Receive a Form [POST]

+ Request (application/json)

        {
            "case_number":"7654321/2017",
            "name":"dodgy_co",
            "contact":"john",
            "building_name":"the_shard",
            "street_name":"downing_street",
            "town":"westminster",
            "county":"",
            "postcode":"wc1 1aa",
            "dx_number":"",
            "contact_number":"",
            "mobile_number":"",
            "contact_preference":"email",
            "email_address":"john@dodgyco.com",
            "fax_number":"",
            "organisation_employ_gb":null,
            "organisation_more_than_one_site":false,
            "employment_at_site_number":null,
            "claimants_name":"jane",
            "agree_with_early_conciliation_details":false,
            "disagree_conciliation_reason":"lorem ipsum conciliation",
            "agree_with_employment_dates":false,
            "employment_start":"Sun, 01 Jan 2017",
            "employment_end":"Sun, 31 Dec 2017",
            "disagree_employment":"lorem ipsum employment",
            "continued_employment":true,
            "agree_with_claimants_description_of_job_or_title":false,
            "disagree_claimants_job_or_title":"lorem ipsum job title",
            "agree_with_claimants_hours":false,
            "queried_hours":32.0,
            "agree_with_earnings_details":false,
            "queried_pay_before_tax":1000.0,
            "queried_pay_before_tax_period":"Monthly",
            "queried_take_home_pay":900.0,
            "queried_take_home_pay_period":"Monthly",
            "agree_with_claimant_notice":false,
            "disagree_claimant_notice_reason":"lorem ipsum notice reason",
            "agree_with_claimant_pension_benefits":false,
            "disagree_claimant_pension_benefits_reason":"lorem ipsum claimant pension",
            "defend_claim":true,
            "defend_claim_facts":"lorem ipsum defence",
            "have_representative":true,
            "type_of_representative":"Private Individual",
            "representative_org_name":"repco ltd",
            "representative_name":"Jane Doe",
            "representative_building":"Rep Building",
            "representative_street":"Rep Street",
            "representative_town":"Rep Town",
            "representative_county":"Rep County",
            "representative_postcode":"WC2 2BB",
            "representative_phone":"0207 987 6543",
            "representative_mobile":"07987654321",
            "representative_dx_number":"dx address",
            "representative_reference":"Rep Ref",
            "representative_contact_preference":"Fax",
            "representative_email":"",
            "representative_fax":"0207 345 6789",
            "representative_disability":true,
            "representative_disability_information":"Lorem ipsum disability",
            "make_employer_contract_claim":true,
            "claim_information":"lorem ipsum info",
            "upload_additional_information":"sample.rtf"
        }

+ Response 201 (application/json)

        {
          "data": {
            "reference": "992000000100",
            "submitted_at": "2018-01-01 12:00:00 GMT+00",
            "pdf": "s3/link/to/form/pdf"
          }
        }


