FORMAT: 1A
HOST: https://et-api-example.com/api

# ET Forms API
This API replaces an existing Jadu system, enabling full functionality within ET1 and ET3 forms.

# Group ET1 [v1/claimants]
Group of all ET1-related resources.

This group is primarily focussed on the ET1 web form.

# Group ET3 [v2/respondents]
Group of all ET3-related resources.

This group is primarily focussed on the ET3 web form.

## Response [v2/respondents/response]
Creates a respondent response within the system and returns confirmation.

### Receive a Form [POST]

Please note an asterisk (\*) denotes an optional field which may not be in the request or may be within the request as `null`.

+ Request (application/json)

        {
            "uuid": "acf1e78a-7c13-4dae-8a68-c43ecfea453d",
            "command": "SerialSequence",
            "data": [
                {
                    "command": "BuildResponse",
                    "data": {
                        "case_number":"1454321/2017",
                        *"claimants_name":"Jane Doe",
                        *"agree_with_early_conciliation_details":false,
                        *"disagree_conciliation_reason":"conciliation info",
                        "agree_with_employment_dates":false,
                        *"employment_start": "2017-01-01",
                        *"employment_end": "2017-12-31",
                        *"disagree_employment":"lorem ipsum employment",
                        *"continued_employment":true,
                        *"agree_with_claimants_description_of_job_or_title":false,
                        *"disagree_claimants_job_or_title":"lorem ipsum job title",
                        *"agree_with_claimants_hours":false,
                        *"queried_hours":32.0,
                        *"agree_with_earnings_details":false,
                        *"queried_pay_before_tax":1000.0,
                        *"queried_pay_before_tax_period":"Monthly",
                        *"queried_take_home_pay":900.0,
                        *"queried_take_home_pay_period":"Monthly",
                        *"agree_with_claimant_notice":false,
                        *"disagree_claimant_notice_reason":"lorem ipsum notice reason",
                        *"agree_with_claimant_pension_benefits":false,
                        *"disagree_claimant_pension_benefits_reason":"lorem ipsum claimant pension",
                        "defend_claim":true,
                        *"defend_claim_facts":"lorem ipsum defence",
                        *"make_employer_contract_claim":true,
                        *"claim_information":"lorem ipsum info",
                        *"email_receipt": "email@recei.pt"
                    },
                    "uuid": "4611f316-f67a-4ccc-9335-df21408e96f6"
                },
                {
                    "command": "BuildRespondent",
                    "data": {
                        "name":"dodgy_co",
                        *"contact":"John Smith",
                        "address_attributes": {
                            "building":"The Shard",
                            "street":"Downing Street",
                            "locality":"Westminster",
                            *"county":"",
                            "post_code":"WC1A 1AA"
                        },
                        *"dx_number":"724060 Derby 21",
                        *"address_telephone_number":"02081234567",
                        *"alt_phone_number":"07123456789",
                        *"contact_preference":"email",
                        *"email_address":"email@domain.com",
                        *"fax_number":"02071234567",
                        *"organisation_employ_gb":100,
                        "organisation_more_than_one_site":true,
                        *"employment_at_site_number":100
                    },
                    "uuid":"d80d85ee-9d5c-4c9c-bd86-aa3da851c622"
                },
                {
                    "command":"BuildRepresentative",
                    "data": {
                        *"name":"Jane Doe",
                        *"organisation_name":"Representative Org",
                        *"address_attributes": {
                            *"building":"Rep Building",
                            *"street":"Rep Street",
                            *"locality":"Rep Town",
                            *"county":"Rep County",
                            *"post_code":"WC2 2BB"
                        },
                        *"address_telephone_number":"02077654321",
                        *"mobile_number":"07987654321",
                        *"representative_type":"Private Individual",
                        *"dx_number":"724060 Derby 21",
                        *"reference":"Rep Ref",
                        *"contact_preference":"Fax",
                        *"email_address":"rep@domain.co.uk",
                        *"fax_number":"02073456789",
                        *"disability":true,
                        *"disability_information":"Lorem ipsum disability"
                    },
                    "uuid":"cdb093bf-82ee-4025-88a8-d00a6717a6aa"
                }
            ]
        }

+ Response 201 (application/json)

        {
            "data": {
                "reference": "992000000100",
                "submitted_at": "2018-01-01",
                "pdf": "s3/link/to/form.pdf",
                "office_address_attributes": {
                    "building":"Office Name",
                    "street":"Office Street",
                    "locality":"Office Town",
                    "county":"Office County",
                    "post_code":"WC3 3CC"
                }
            }
        }

